# Generated by Django 3.1.3 on 2020-11-05 15:20

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 15, 20, 29, 84187, tzinfo=utc), verbose_name='追加日時'),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 15, 20, 29, 84187, tzinfo=utc), verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='note',
            name='like',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='note',
            name='nigami',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='苦味'),
        ),
        migrations.AlterField(
            model_name='note',
            name='sanmi',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='酸味'),
        ),
    ]
