# Generated by Django 3.1.3 on 2020-11-05 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20201106_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(default='', verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='note',
            name='like',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='note',
            name='nigami',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='苦味'),
        ),
        migrations.AlterField(
            model_name='note',
            name='sanmi',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='酸味'),
        ),
    ]
