# Generated by Django 3.1.3 on 2020-11-23 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0007_auto_20201123_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='public',
            field=models.CharField(default='False', max_length=10, verbose_name='公開'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
